### ISSUE TITLE
Difference to MixedReality-WebRTC

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/winrtc#36]
The [MixedReality-WebRTC](https://github.com/microsoft/MixedReality-WebRTC) from Microsoft also provides a wrapper on libwebrtc. What Is the difference between that project and this one? 

Is this summary correct?
 - `winrtc` provides a WinRT interface to `libwebrtc` (plus XAML control and nuget package)
 - `mrwebrtc` (Mixed Reality WebRTC) provides a UWP interface to `libwebrtc` ` (plus nuget package)

Is there any likelihood that this project will ever work with Microsoft Teams so that a native app can make/receive calls to Teams given that Teams is using WebRTC under the hood?

**Comment by LoadLibrary** [comment]
MixedReality-WebRTC aims to fulfill the RTC needs related to mixed reality use cases. MixedReality-WebRTC is based on the deprecated [WebRTC-UWP](https://github.com/webrtc-uwp) project which is parked at an old version of Chrome (m71).

WinRTC is the next gen of RTC for Windows native apps. It encompasses UWP, Desktop (Win32 & .Net) and IoT scenarios as well (not only HoloLens scenarios). WinRTC is currently based on Chrome m80. WinRTC is not a fork of WebRTC.org, so it is easy to keep it up to date with the code shipped inside web browsers.

I'm currently working towards bringing WinRTC in parity with WebRTC-UWP. Once parity is reached, MixedReality-WebRTC will take WinRTC as dependency instead of WebRTC-UWP. AFAIK, MixedReality-WebRTC is using this [branch](https://github.com/microsoft/MixedReality-WebRTC/tree/experimental/undock) for undocking from WebRTC-UWP.

A better summary would be:
- ``winrtc`` provides / has plans to provide:
1. fixes for building WebRTC.org code on UWP
2. WinRT projections for WebRTC APIs
3. Xaml component
4. NuGet packages for items 1, 2 and 3.

Please take a look at our //Build [session](https://www.youtube.com/watch?v=GKrTmgZT-EA) and [Q&A](https://www.youtube.com/watch?v=AsjgLAtzUT4) for more info about WinRTC components.

> Is there any likelihood that this project will ever work with Microsoft Teams so that a native app can make/receive calls to Teams given that Teams is using WebRTC under the hood?

Microsoft Teams is a very complex application with a even more complex back end. I can't speculate on the likelihood of having WinRTC interacting with Teams. However, I can say that native apps using WinRTC should be able to establish connections to other WebRTC compliant apps (including web browsers).

**Comment by sipsorcery** [comment]
Thx for the info. I only found out about this repo from watching the //Build session :).

Great to here there's consolidation happening with MS WebRTC support. Hopefully Teams will expose a `Peer Connection` like API at some point.

In the Q&A presentation there was a question about using `WinRTC` to access an RTSP source. The answer (from you I think) was that it would be no problem. How would that be accomplished? Would if be done by using `Windows Media Foundation` to create an `IMFMediaSource` to allow the RTSP stream to be treated the same as a webcam? It's definitely not possible to use `libwebrtc` to connect to an RTSP server or for the RTSP server to do the ICE connectivity checks etc.

**Comment by LoadLibrary** [comment]
We definitely need better names for all this components. When I read ``libwebrtc`` I think about the library generated after WebRTC.org code without any fixes. ``libwebrtc`` camera module is based on legacy DirectShow that is not supported by UWP. Maybe you're talking about the camera module from MixedReality-WebRTC that is based upon WebRTC-UWP. The WebRTC-UWP camera module is based on a Media Foundation implementation. WinRTC camera module is based on the WinRT's Windows::Media::Capture APIs.

I might be misunderstanding your question. I didn't test WinRTC camera module with a network camera. I might be wrong, but it is my understanding that the WinRT APIs for device enumeration will return network cameras as valid devices to capture frames from.

**Comment by sipsorcery** [comment]
I was using `libwebrtc` to refer to Google's open source WebRTC implementation and documented at webrtc.org. Perhaps the Windows build produces a different library name these days? It's been a few years since I built it.

Ah I think I get what you mean about supporting RTSP now. If the driver for a particular Windows camera device supports RTSP under the hood then it can be used with `DirectShow` or `Windows Media Foundation` just the same as a standard webcam. But what won't be possible is to connect the `winrtc` (or `libwebrtc`) to an external RTSP source such as `ffmpeg` running in a console.

You may have already seen these items but if not it seems like Google may not be that far away from switching to Media Foundation for `libwebrtc`. The switch has already been made in [Chromium](https://source.chromium.org/chromium/chromium/src/+/master:media/capture/video/win/video_capture_device_mf_win.cc) with corresponding [discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=735576). It would seem strange for Google to maintain two separate Windows video capture mechanisms in sister components.

**Comment by LoadLibrary** [comment]
> It would seem strange for Google to maintain two separate Windows video capture mechanisms in sister components.

I cannot talk for Google. The discussion you've [cited](https://bugs.chromium.org/p/chromium/issues/detail?id=735576) was started in June 2017 and resolved in April 2019. We're in June 2020 and the Windows video capture module in the standalone WebRTC is not the same as the one shipping in the web browser.

**Comment by qian256** [comment]
Does WinRTC support mixed reality capture (via AddVideoEffectAsync) on HoloLens like MixedReality-WebRTC?
