### ISSUE TITLE
libwebrtc m84 does not build on UWP ARM64

### ISSUE THREAD

**Issue by fiban-havok** [microsoft/winrtc#44]
Building after applying the patches in the m84 directory generates plenty of errors. See attached log for a comprehensive list (the used args.gn is also attached).
[errors.zip](https://github.com/microsoft/winrtc/files/4865618/errors.zip)

**Comment by LoadLibrary** [comment]
The used build args are different from the ones used for validating the patches.

The following categories are observed from the attached build log:

- BoringSSL not knowing the target platform
- libjpeg_turbo unique use of C and Neon instructions
- aec3 code issue with switch statement contains 'default' but no 'case' labels

WinRTC m80 has fixes for that issues. The fixes might not be copied over to m84 because some issue with the build process (left overs).

I'm going to clone WebRTC from scratch, apply the patches and build with both set of gn args.
